// src/components/BookmarksHeaderLink.svelte
<script lang="ts">
  import { onDestroy, onMount } from "svelte";

  let countLabel = "";

  function updateCount() {
    if (typeof window === "undefined") return;
    const raw = localStorage.getItem("saved-posts");
    if (!raw) {
      countLabel = "";
      return;
    }

    try {
      const parsed = JSON.parse(raw);
      const count = Array.isArray(parsed) ? parsed.length : 0;
      countLabel = count > 0 ? String(count) : "";
    } catch {
      countLabel = "";
    }
  }

  onMount(() => {
    updateCount();
    window.addEventListener("storage", updateCount);
    document.addEventListener("saved-posts-changed", updateCount);
  });

  onDestroy(() => {
    if (typeof window === "undefined") return;
    window.removeEventListener("storage", updateCount);
    document.removeEventListener("saved-posts-changed", updateCount);
  });
</script>

<a
  href="/bookmarks"
  class=" md:order-0 inline-flex items-center gap-2 rounded-full border border-black bg-black px-3 py-1.5 text-sm font-medium text-white transition-colors hover:bg-[#2b2b2b]"
>
  <span>Закладки</span>
  {#if countLabel}
    <span class="inline-flex min-w-5 items-center justify-center rounded-full bg-white px-1.5 py-0.5 text-xs font-semibold text-black">
      {countLabel}
    </span>
  {/if}
</a>

// src/components/BookmarksHeaderLink.tsx
import { createSignal, onCleanup, onMount, Show } from "solid-js";
import { SAVED_POSTS_CHANGED_EVENT, loadSavedPosts } from "@/js/bookmarks";

export default function BookmarksHeaderLink() {
	const [count, setCount] = createSignal(0);

	const sync = () => setCount(loadSavedPosts().length);

	onMount(() => {
		sync();
		window.addEventListener("storage", sync);
		document.addEventListener(SAVED_POSTS_CHANGED_EVENT, sync);
	});

	onCleanup(() => {
		if (typeof window === "undefined") return;
		window.removeEventListener("storage", sync);
		document.removeEventListener(SAVED_POSTS_CHANGED_EVENT, sync);
	});

	return (
		<a
			href="/bookmarks"
			aria-label="Открыть закладки"
			class="inline-flex items-center gap-2 rounded-full border border-[var(--border-soft)] bg-[var(--bg-elevated)] px-3 py-1.5 text-sm font-medium text-[var(--text-main)] transition-colors hover:bg-[var(--bg-soft)]"
		>
			<span>Закладки</span>
			<Show when={count() > 0}>
				<span class="inline-flex min-w-5 items-center justify-center rounded-full bg-[var(--text-main)] px-1.5 py-0.5 text-xs font-semibold text-[var(--bg-page)]">
					{count()}
				</span>
			</Show>
		</a>
	);
}
